---
- hosts: nodejs-onprem
  connection: ssh
  vars:
    _baseDir: "{{ BASE_DIR }}"
    _varsPath: "{{ _baseDir }}/vars"
    _rolesPath: "{{ _baseDir }}/roles"
  roles:
    - role: "{{ _rolesPath }}/ansible-role-nvm"
      nvm_env: system
      nvm_version: v0.32.0
      nvm_default_node_version: v0.10.35
      nvm_node_versions:
        - v0.12.7
        - v0.10.35
      nvm_global_packages: [forever]
